language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cwood89/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cwood89/docker-react npm run test